# config/bronze_etl_plan.yml
bronze_etl_plan:
  type:
    endpoint: "https://pokeapi.co/api/v2/type"
    class: "Type"
    call_mode: "single"
    batch_size: 300
    dependencies: [] 
  move:
    endpoint: "https://pokeapi.co/api/v2/move"
    class: "Move"
    call_mode: "batch"
    batch_size: 300
    dependencies: ["type"] 
  ability:
    endpoint: "https://pokeapi.co/api/v2/ability"
    class: "Ability"
    call_mode: "batch"
    batch_size: 300
    dependencies: ["move"] 
  pokemon:
    endpoint: "https://pokeapi.co/api/v2/pokemon"
    class: "Pokemon"
    call_mode: "batch"
    batch_size: 300
    dependencies: ["ability"]
  pokemon_species:
    endpoint: "https://pokeapi.co/api/v2/pokemon-species"
    class: "PokemonSpecies"
    call_mode: "batch"
    batch_size: 300
    dependencies: ["pokemon"]
