process_bronze:
    type:
        class: "Type"
        return_multiple: False
        dependencies: []
    move:
        class: "Move"
        return_multiple: False
        dependencies: ["type"] 
    ability:
        class: "Ability"
        return_multiple: False
        dependencies: ["move"] 
    pokemon:
        class: "Pokemon"
        return_multiple: True
        dependencies: ["ability"]
    pokemon_species:
        class: "PokemonSpecies"
        return_multiple: False
        dependencies: ["pokemon"]
process_silver:
    pokemon_stats_flattened:
        dependencies: ["pokemon_species"]
    pokemon_moves_summary:
        dependencies: ["pokemon_stats_flattened"]
    pokemon_abilities_summary:
        dependencies: ["pokemon_moves_summary"]
    type_combo:
        dependencies: ["pokemon_abilities_summary"]
    pokemon_master:
        dependencies: ["type_combo"]